name: Feature Request
description: Suggest a new feature or enhancement for 8004scan
title: "[Feature]: "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Thank you for your feature suggestion!

        We love hearing ideas from our community. Please fill out the form below to help us understand your request.

        **Before submitting**, please search [existing issues](https://github.com/alt-research/8004scan-issue-tracker/issues) to see if this feature has already been requested.

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What area of 8004scan does this feature relate to?
      options:
        - Agent Discovery & Search
        - Agent Rankings & Scoring
        - Validation System
        - User Experience (UX)
        - User Interface (UI)
        - Authentication & Wallets
        - Notifications & Alerts
        - API & Integrations
        - Analytics & Insights
        - Mobile Experience
        - Accessibility
        - Performance
        - Security
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is your feature request related to a frustration?
      placeholder: |
        I'm always frustrated when...
        Currently, it's difficult to...
        There's no way to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: |
        I would like to be able to...
        The feature should...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: |
        I've tried...
        Another approach could be...

  - type: dropdown
    id: priority
    attributes:
      label: Priority (from your perspective)
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would improve my experience
        - Important for my use case
        - Critical - blocking my usage
    validations:
      required: true

  - type: dropdown
    id: user-type
    attributes:
      label: User Type
      description: What best describes you?
      options:
        - Casual user / Explorer
        - Agent developer
        - Agent validator
        - DApp developer / Integrator
        - Researcher
        - Other
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case for this feature
      placeholder: |
        As a [type of user], I want to [goal] so that [benefit]...
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups / Examples
      description: If you have any mockups, sketches, or examples from other platforms, please share them
      placeholder: Drag and drop images here or paste URLs...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, links, or references that might help us understand your request?

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be interested in helping with this feature?
      options:
        - label: I would be willing to help test this feature
        - label: I would be willing to help with documentation
        - label: I would be willing to provide feedback during development

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues and this is not a duplicate
          required: true
        - label: I have provided a clear problem statement and proposed solution
          required: true
