name: General Feedback
description: Share your experience, suggestions, or thoughts about 8004scan
title: "[Feedback]: "
labels: ["feedback"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## We'd love to hear from you!

        Your feedback helps us make 8004scan better for everyone. Whether it's praise, criticism, or suggestions - we're all ears!

  - type: dropdown
    id: feedback-type
    attributes:
      label: Feedback Type
      description: What kind of feedback would you like to share?
      options:
        - General impression
        - User experience feedback
        - Design / UI feedback
        - Performance feedback
        - Content / Documentation feedback
        - Comparison with other platforms
        - Suggestion
        - Compliment
        - Concern
        - Other
    validations:
      required: true

  - type: dropdown
    id: sentiment
    attributes:
      label: Overall Sentiment
      description: How would you describe your overall experience?
      options:
        - Very positive
        - Positive
        - Neutral
        - Negative
        - Very negative
    validations:
      required: true

  - type: textarea
    id: feedback
    attributes:
      label: Your Feedback
      description: Please share your thoughts, experiences, or suggestions
      placeholder: |
        What did you like?
        What could be improved?
        What was confusing?
        What was delightful?
    validations:
      required: true

  - type: dropdown
    id: experience-level
    attributes:
      label: Experience with 8004scan
      description: How long have you been using 8004scan?
      options:
        - First time user
        - Less than a week
        - 1-4 weeks
        - 1-3 months
        - More than 3 months
    validations:
      required: true

  - type: dropdown
    id: user-type
    attributes:
      label: User Type
      description: What best describes you?
      options:
        - Casual user / Explorer
        - Agent developer
        - Agent validator
        - DApp developer / Integrator
        - Researcher
        - Other
    validations:
      required: true

  - type: textarea
    id: favorite
    attributes:
      label: What do you like most about 8004scan?
      placeholder: Tell us what's working well...

  - type: textarea
    id: improvement
    attributes:
      label: What would you most like to see improved?
      placeholder: Tell us what could be better...

  - type: dropdown
    id: recommend
    attributes:
      label: Would you recommend 8004scan to others?
      description: On a scale of likelihood
      options:
        - Definitely yes
        - Probably yes
        - Not sure
        - Probably not
        - Definitely not

  - type: textarea
    id: comparison
    attributes:
      label: Comparison with Other Platforms
      description: How does 8004scan compare to other platforms you've used? (optional)
      placeholder: |
        Compared to [other platform], 8004scan is...

  - type: textarea
    id: additional
    attributes:
      label: Additional Comments
      description: Anything else you'd like to share?

  - type: checkboxes
    id: follow-up
    attributes:
      label: Follow-up
      description: Would you like us to follow up?
      options:
        - label: Yes, I'm open to being contacted for more details
        - label: I would like to participate in user research / interviews

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have not included any sensitive personal information
          required: true
